In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("data\\processed\\final_transactions.csv")
df

,CustomerID,TransactionID,Date,Description,Merchant,Amount,Balance,SubscriptionFlag,Transaction_Type,Frequency,Next_Expected_Date
0,C1,T2,2025-01-02,payment to cafe coffee day,cafe coffee day,-1691,53492,0,Non-Subscription,Irregular,2025-06-20 14:23:59.999999999
1,C1,T7,2025-01-05,payment to cafe coffee day,cafe coffee day,-1361,48520,0,Non-Subscription,Irregular,2025-06-20 14:23:59.999999999
2,C1,T9,2025-01-06,payment to cafe coffee day,cafe coffee day,-1099,46833,0,Non-Subscription,Irregular,2025-06-20 14:23:59.999999999
3,C1,T17,2025-01-14,payment to cafe coffee day,cafe coffee day,-833,41067,0,Non-Subscription,Irregular,2025-06-20 14:23:59.999999999
4,C1,T60,2025-02-20,payment to cafe coffee day,cafe coffee day,-1477,98335,0,Non-Subscription,Irregular,2025-06-20 14:23:59.999999999
...,...,...,...,...,...,...,...,...,...,...,...
95319,C99,T19590,2025-05-10,payment to zomato,zomato,-1358,86,0,Non-Subscription,Irregular,2025-06-27 18:51:25.714285714
95320,C99,T19592,2025-05-12,payment to zomato,zomato,-1288,86,0,Non-Subscription,Irregular,2025-06-27 18:51:25.714285714
95321,C99,T19601,2025-05-23,payment to zomato,zomato,-292,86,0,Non-Subscription,Irregular,2025-06-27 18:51:25.714285714
95322,C99,T19604,2025-05-27,payment to zomato,zomato,-563,86,0,Non-Subscription,Irregular,2025-06-27 18:51:25.714285714
95323,C99,T19627,2025-06-17,payment to zomato,zomato,-1916,9087,0,Non-Subscription,Irregular,2025-06-27 18:51:25.714285714

In [6]:
df["Frequency"].value_counts()

Frequency
Weekly           65175
Irregular        23221
Monthly           6902
Not Recurring       26
Name: count, dtype: int64

In [10]:
df[df["Frequency"] != "Not Recurring"]

,CustomerID,TransactionID,Date,Description,Merchant,Amount,Balance,SubscriptionFlag,Transaction_Type,Frequency,Next_Expected_Date
0,C1,T2,2025-01-02,payment to cafe coffee day,cafe coffee day,-1691,53492,0,Non-Subscription,Irregular,2025-06-20 14:23:59.999999999
1,C1,T7,2025-01-05,payment to cafe coffee day,cafe coffee day,-1361,48520,0,Non-Subscription,Irregular,2025-06-20 14:23:59.999999999
2,C1,T9,2025-01-06,payment to cafe coffee day,cafe coffee day,-1099,46833,0,Non-Subscription,Irregular,2025-06-20 14:23:59.999999999
3,C1,T17,2025-01-14,payment to cafe coffee day,cafe coffee day,-833,41067,0,Non-Subscription,Irregular,2025-06-20 14:23:59.999999999
4,C1,T60,2025-02-20,payment to cafe coffee day,cafe coffee day,-1477,98335,0,Non-Subscription,Irregular,2025-06-20 14:23:59.999999999
...,...,...,...,...,...,...,...,...,...,...,...
95319,C99,T19590,2025-05-10,payment to zomato,zomato,-1358,86,0,Non-Subscription,Irregular,2025-06-27 18:51:25.714285714
95320,C99,T19592,2025-05-12,payment to zomato,zomato,-1288,86,0,Non-Subscription,Irregular,2025-06-27 18:51:25.714285714
95321,C99,T19601,2025-05-23,payment to zomato,zomato,-292,86,0,Non-Subscription,Irregular,2025-06-27 18:51:25.714285714
95322,C99,T19604,2025-05-27,payment to zomato,zomato,-563,86,0,Non-Subscription,Irregular,2025-06-27 18:51:25.714285714
95323,C99,T19627,2025-06-17,payment to zomato,zomato,-1916,9087,0,Non-Subscription,Irregular,2025-06-27 18:51:25.714285714

In [12]:
risk_df = pd.read_csv("outputs\\risk_scoring_output.csv")

In [13]:
risk_df["Risk_Level"].value_counts()

Risk_Level
Low     4233
High       7
Name: count, dtype: int64