## **Recurring Pattern Detection**

In [4]:
import sys, os
project_root = os.path.abspath("..")
if project_root not in sys.path:
    sys.path.append(project_root)

print("Project root added:", project_root)

Project root added: c:\Users\Samyak.Bora\Desktop\Training\Assessments_And_Projects\Group_Project\Final

In [1]:
import pandas as pd
import numpy as np
from datetime import timedelta
from dateutil.relativedelta import relativedelta

# Load main cleaned transactions dataset
df = pd.read_csv("..\\data\\subscription_dataset_cleaned.csv")
df["Date"] = pd.to_datetime(df["Date"])

# Load NLP subscription detection output (produced in FR3)
nlp_df = pd.read_csv("..\\data\\recurring_patterns.csv")
df["Date"] = pd.to_datetime(df["Date"])

df.head()

,CustomerID,TransactionID,Date,Description,Merchant,Amount,Balance,SubscriptionFlag,Month,DayOfWeek,TransactionType,Category
0,C1,T1,2025-01-01,Payment to Cafe Coffee Day,Cafe Coffee Day,-1889,6136,0,2025-01,Wednesday,Debit,Food
1,C1,T2,2025-01-01,Payment to Flipkart,Flipkart,-955,5181,0,2025-01,Wednesday,Debit,Shopping
2,C1,T3,2025-01-02,Salary Credit,Employer,49954,55135,0,2025-01,Thursday,Credit,Others
3,C1,T4,2025-01-02,Payment to Reliance Smart,Reliance Smart,-1582,53553,0,2025-01,Thursday,Debit,Shopping
4,C1,T5,2025-01-02,Payment to Petrol Pump,Petrol Pump,-1257,52296,0,2025-01,Thursday,Debit,Fuel

In [3]:
df["DetectedSubscription"] = nlp_df["PredictedSubscription"]

KeyError: 'PredictedSubscription'

In [38]:
nlp_df.head()

,CustomerID,Merchant,Recurrence,RecurringDay,LastTransactionDate,NextExpectedDate,TotalOccurrences
0,C1,Cafe Coffee Day,WEEKLY,14,2025-06-11,2025-06-18,24
1,C1,Flipkart,WEEKLY,1,2025-06-14,2025-06-21,23
2,C1,Employer,MONTHLY,2,2025-06-02,2025-07-02,6
3,C1,Petrol Pump,WEEKLY,3,2025-06-29,2025-07-06,26
4,C1,Electricity Bill,MONTHLY,3,2025-06-03,2025-07-03,6

In [42]:
nlp_df.columns

Index(['CustomerID', 'Merchant', 'Recurrence', 'RecurringDay',
       'LastTransactionDate', 'NextExpectedDate', 'TotalOccurrences'],
      dtype='object')

**Extract Subscription Flag from spaCy Result**

In [41]:
# Convert spaCyResult to a simple 0/1 subscription flag
def extract_flag(text):
    if isinstance(text, str) and "Subscription" in text:
        return 1
    return 0

df["DetectedSubscription"] = nlp_df["spaCyResult"].apply(extract_flag)
df.head()

KeyError: 'spaCyResult'

**Build Dynamic Subscription Merchant List**

In [ ]:
subscription_merchants = (
    df[df["DetectedSubscription"] == 1]["Merchant"]
        .str.lower()

,CustomerID,Merchant,Recurrence,RecurringDay,LastTransactionDate,NextExpectedDate,TotalOccurrences
0,C1,Cafe Coffee Day,WEEKLY,14,2025-06-11,2025-06-18,24
1,C1,Flipkart,WEEKLY,1,2025-06-14,2025-06-21,23
2,C1,Employer,MONTHLY,2,2025-06-02,2025-07-02,6
3,C1,Petrol Pump,WEEKLY,3,2025-06-29,2025-07-06,26
4,C1,Electricity Bill,MONTHLY,3,2025-06-03,2025-07-03,6
...,...,...,...,...,...,...,...
4136,C99,Employer,MONTHLY,2,2025-06-02,2025-07-02,6
4137,C99,Swiggy,WEEKLY,25,2025-06-23,2025-06-30,33
4138,C99,Medical Store,WEEKLY,9,2025-06-25,2025-07-02,21
4139,C99,Electricity Bill,MONTHLY,11,2025-06-11,2025-07-11,6
4140,C99,Uber,WEEKLY,4,2025-06-18,2025-06-25,21

**Extract Detected Subscription Flag from spaCy Output**

In [ ]:
# # Training Loop
# n_iter = 10
# optimizer = nlp.initialize()

# for epoch in range(n_iter):
#     random.shuffle(train_data)
#     losses = {}

#     batches = minibatch(train_data, size=compounding(4.0, 32.0, 1.5))

#     for batch in batches:
#         examples = []
#         for text, annotations in batch:
#             doc = nlp.make_doc(text)
#             examples.append(Example.from_dict(doc, annotations))
#         nlp.update(examples, sgd=optimizer, losses=losses)

#     print(f"Epoch {epoch+1}/{n_iter}, Loss: {losses}")

Epoch 1/10, Loss: {'textcat_multilabel': 0.6193333964600336}
Epoch 2/10, Loss: {'textcat_multilabel': 1.2553283594424203e-06}
Epoch 3/10, Loss: {'textcat_multilabel': 4.0881065122705396e-07}
Epoch 4/10, Loss: {'textcat_multilabel': 1.4279217421669932e-07}
Epoch 5/10, Loss: {'textcat_multilabel': 5.40176219943414e-08}
Epoch 6/10, Loss: {'textcat_multilabel': 2.1644825331482327e-08}
Epoch 7/10, Loss: {'textcat_multilabel': 9.746361631494428e-09}
Epoch 8/10, Loss: {'textcat_multilabel': 4.66132700445215e-09}
Epoch 9/10, Loss: {'textcat_multilabel': 2.3371203418734443e-09}
Epoch 10/10, Loss: {'textcat_multilabel': 1.401930615216665e-09}

In [29]:
# Convert spaCyResult text into a 0/1 subscription flag
def extract_subscription_flag(result):
    if isinstance(result, str) and "Subscription" in result:
        return 1
    return 0

df["DetectedSubscription"] = nlp_df["spaCyResult"].apply(extract_subscription_flag)
df.head()

KeyError: 'spaCyResult'

In [24]:
# Merge so we can use detected subscription status
df["DetectedSubscription"] = nlp_detected["DetectedSubscription"]
df.head()

KeyError: 'DetectedSubscription'

___
___

In [2]:
import pandas as pd
import numpy as np
from datetime import timedelta

# Load cleaned transactions dataset
df = pd.read_csv("..\\data\\subscription_dataset_cleaned.csv")
df["Date"] = pd.to_datetime(df["Date"])

df.head()

,CustomerID,TransactionID,Date,Description,Merchant,Amount,Balance,SubscriptionFlag,Month,DayOfWeek,TransactionType,Category
0,C1,T1,2025-01-01,Payment to Cafe Coffee Day,Cafe Coffee Day,-1889,6136,0,2025-01,Wednesday,Debit,Food
1,C1,T2,2025-01-01,Payment to Flipkart,Flipkart,-955,5181,0,2025-01,Wednesday,Debit,Shopping
2,C1,T3,2025-01-02,Salary Credit,Employer,49954,55135,0,2025-01,Thursday,Credit,Others
3,C1,T4,2025-01-02,Payment to Reliance Smart,Reliance Smart,-1582,53553,0,2025-01,Thursday,Debit,Shopping
4,C1,T5,2025-01-02,Payment to Petrol Pump,Petrol Pump,-1257,52296,0,2025-01,Thursday,Debit,Fuel

In [17]:
df["SubscriptionFlag"].value_counts()

SubscriptionFlag
0    93088
1     6108
Name: count, dtype: int64

**Compute Date Intervals**

In [4]:
""" Calculate day differences between consecutive dates.
    Used to detect weekly / monthly patterns.
"""
def compute_intervals(dates):
    dates = sorted(dates)  # Ensure chronological order
    intervals = [
        (dates[i] - dates[i-1]).days
        for i in range(1, len(dates))
    ]
    return intervals

**Determine Recurrence Type (Weekly / Monthly)**

In [5]:
""" Classifies recurrence based on average interval:
    - Weekly: 5 to 9 days
    - Monthly: 28 to 32 days
"""
def classify_recurrence(intervals):
    
    if len(intervals) < 2:
        return None  # Not enough data

    avg_gap = np.mean(intervals)

    if 5 <= avg_gap <= 9:
        return "WEEKLY"
    if 28 <= avg_gap <= 32:
        return "MONTHLY"

    return None

**Detect Recurring Patterns + Next Date**

In [11]:
from dateutil.relativedelta import relativedelta


patterns = []

for customer in df["CustomerID"].unique():
    df_cust = df[df["CustomerID"] == customer]

    for merchant in df_cust["Merchant"].unique():
        df_cm = df_cust[df_cust["Merchant"] == merchant]

        # Need at least 3 occurrences to consider recurring
        if len(df_cm) < 3:
            continue

        # Extract dates
        dates = sorted(df_cm["Date"].tolist())
        intervals = compute_intervals(dates)

        # Determine recurrence type
        recurrence = classify_recurrence(intervals)
        if recurrence is None:
            continue  # Not recurring

        # Recurring day (e.g., 5th of every month)
        recurring_day = df_cm["Date"].dt.day.mode()[0]

        # Predict next expected date
        last_date = dates[-1]

        if recurrence == "WEEKLY":
            next_expected = last_date + timedelta(days=7)
        elif recurrence == "MONTHLY":
            # Correct month-handling including Feb and month-end cases
            next_expected = last_date + relativedelta(months=1)

        # elif recurrence == "MONTHLY":
        #     next_expected = last_date + timedelta(days=30)  # or use avg interval

        patterns.append({
            "CustomerID": customer,
            "Merchant": merchant,
            "Recurrence": recurrence,
            "RecurringDay": int(recurring_day),
            "LastTransactionDate": last_date.date(),
            "NextExpectedDate": next_expected.date(),
            "TotalOccurrences": len(df_cm)
        })

**Convert to DataFrame**

In [12]:
patterns_df = pd.DataFrame(patterns)
patterns_df

,CustomerID,Merchant,Recurrence,RecurringDay,LastTransactionDate,NextExpectedDate,TotalOccurrences
0,C1,Cafe Coffee Day,WEEKLY,14,2025-06-11,2025-06-18,24
1,C1,Flipkart,WEEKLY,1,2025-06-14,2025-06-21,23
2,C1,Employer,MONTHLY,2,2025-06-02,2025-07-02,6
3,C1,Petrol Pump,WEEKLY,3,2025-06-29,2025-07-06,26
4,C1,Electricity Bill,MONTHLY,3,2025-06-03,2025-07-03,6
...,...,...,...,...,...,...,...
4136,C99,Employer,MONTHLY,2,2025-06-02,2025-07-02,6
4137,C99,Swiggy,WEEKLY,25,2025-06-23,2025-06-30,33
4138,C99,Medical Store,WEEKLY,9,2025-06-25,2025-07-02,21
4139,C99,Electricity Bill,MONTHLY,11,2025-06-11,2025-07-11,6
4140,C99,Uber,WEEKLY,4,2025-06-18,2025-06-25,21

**Save for ML / Dashboard**

In [13]:
patterns_df.to_csv("..\\data\\recurring_patterns.csv", index=False)
patterns_df

,CustomerID,Merchant,Recurrence,RecurringDay,LastTransactionDate,NextExpectedDate,TotalOccurrences
0,C1,Cafe Coffee Day,WEEKLY,14,2025-06-11,2025-06-18,24
1,C1,Flipkart,WEEKLY,1,2025-06-14,2025-06-21,23
2,C1,Employer,MONTHLY,2,2025-06-02,2025-07-02,6
3,C1,Petrol Pump,WEEKLY,3,2025-06-29,2025-07-06,26
4,C1,Electricity Bill,MONTHLY,3,2025-06-03,2025-07-03,6
...,...,...,...,...,...,...,...
4136,C99,Employer,MONTHLY,2,2025-06-02,2025-07-02,6
4137,C99,Swiggy,WEEKLY,25,2025-06-23,2025-06-30,33
4138,C99,Medical Store,WEEKLY,9,2025-06-25,2025-07-02,21
4139,C99,Electricity Bill,MONTHLY,11,2025-06-11,2025-07-11,6
4140,C99,Uber,WEEKLY,4,2025-06-18,2025-06-25,21